from . import wc_instance
from . import wc_order_status
from . import wc_tags
from . import wc_product_category
from . import wc_product
from . import wc_product_image
from . import product
from . import res_partner
from . import sale_order
from . import stock_picking
from . import account_invoice
from . import wc_process_job
from . import wc_payment_gateway
from . import wc_coupons
from . import wc_product_attribute
from . import stock_inventory
